---
- name: primo play di prova
  hosts: all
  gather_facts: false
  tasks:
    - name: "*** BUILD ***"
      debug:
        msg: "Eseguita la build della app"

    - name: "*** TEST ***"
      debug:
        msg: "Eseguiti i test della app"

    - name: "*** DEPLOY ***"
      debug:
        msg: "Eseguito il deploy ella app"
