---
- name: primo play di finta pipeline CI/CD lallero
  hosts: all
  gather_facts: false
  tasks:
    - name: "*** BUILD ***"
      debug:
        msg: "Eseguita la build della app"

    - name: "*** TEST ***"
      debug:
        msg: "Eseguiti i test della app"

    - name: "*** DEPLOY ***"
      debug:
        msg: "Eseguito il deploy della app"

    - name: Ensure terzo_file.md is copied to dest host
      copy:
        src: terzo_file.md
        dest: /tmp/